-- Privacy-preserving writer application rate limits.
-- Only a one-way SHA-256 hash is stored; raw IP addresses never reach the database.

CREATE TABLE IF NOT EXISTS public.writer_application_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_writer_application_attempts_hash_created
  ON public.writer_application_attempts (ip_hash, created_at DESC);

ALTER TABLE public.writer_application_attempts ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.consume_writer_application_attempt(
  p_ip_hash text,
  p_limit integer DEFAULT 3,
  p_window interval DEFAULT interval '24 hours'
)
RETURNS TABLE (allowed boolean, attempts integer, retry_after_seconds integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
  v_oldest timestamptz;
BEGIN
  IF p_ip_hash IS NULL OR length(p_ip_hash) <> 64 OR p_limit < 1 THEN
    RAISE EXCEPTION 'Invalid rate-limit parameters';
  END IF;

  -- Serialize requests for the same hash to prevent concurrent limit bypasses.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_ip_hash, 0));

  SELECT count(*)::integer, min(created_at)
  INTO v_count, v_oldest
  FROM public.writer_application_attempts
  WHERE ip_hash = p_ip_hash
    AND created_at > now() - p_window;

  IF v_count >= p_limit THEN
    RETURN QUERY SELECT
      false,
      v_count,
      greatest(1, ceil(extract(epoch FROM ((v_oldest + p_window) - now())))::integer);
    RETURN;
  END IF;

  INSERT INTO public.writer_application_attempts (ip_hash) VALUES (p_ip_hash);
  RETURN QUERY SELECT true, v_count + 1, 0;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_writer_application_attempt(text, integer, interval) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.consume_writer_application_attempt(text, integer, interval) TO service_role;

COMMENT ON TABLE public.writer_application_attempts IS
  'Writer application timestamps keyed by a salted SHA-256 IP hash. Raw IP addresses are never stored.';
