-- Harden newsletter signup against automated spam submissions, matching the
-- contact/advertising-enquiry pipeline hardened in 20260904120000. The route
-- previously inserted directly with the anon key: no honeypot, no rate limit,
-- no content validation, and no name fields — which is how "hoax subscriber"
-- rows got in with nothing but an email address.

ALTER TABLE IF EXISTS public.subscribers
  ADD COLUMN IF NOT EXISTS first_name text NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS public.subscribers
  ADD COLUMN IF NOT EXISTS last_name text NOT NULL DEFAULT '';

COMMENT ON COLUMN public.subscribers.first_name IS
  'Required for new signups (enforced by the RLS insert policy below and by app-level validation). Existing pre-hardening rows are backfilled empty rather than fabricated.';
COMMENT ON COLUMN public.subscribers.last_name IS
  'Required for new signups (enforced by the RLS insert policy below and by app-level validation). Existing pre-hardening rows are backfilled empty rather than fabricated.';

CREATE TABLE IF NOT EXISTS public.newsletter_subscribe_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_newsletter_subscribe_attempts_hash_created
  ON public.newsletter_subscribe_attempts (ip_hash, created_at DESC);

ALTER TABLE public.newsletter_subscribe_attempts ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.consume_newsletter_subscribe_attempt(
  p_ip_hash text,
  p_limit integer DEFAULT 8,
  p_window interval DEFAULT interval '1 hour'
)
RETURNS TABLE (allowed boolean, attempts integer, retry_after_seconds integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
  v_oldest timestamptz;
BEGIN
  IF p_ip_hash IS NULL OR length(p_ip_hash) <> 64 OR p_limit < 1 THEN
    RAISE EXCEPTION 'Invalid rate-limit parameters';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(p_ip_hash, 0));

  SELECT count(*)::integer, min(created_at)
  INTO v_count, v_oldest
  FROM public.newsletter_subscribe_attempts
  WHERE ip_hash = p_ip_hash
    AND created_at > now() - p_window;

  IF v_count >= p_limit THEN
    RETURN QUERY SELECT
      false,
      v_count,
      greatest(1, ceil(extract(epoch FROM ((v_oldest + p_window) - now())))::integer);
    RETURN;
  END IF;

  INSERT INTO public.newsletter_subscribe_attempts (ip_hash) VALUES (p_ip_hash);
  RETURN QUERY SELECT true, v_count + 1, 0;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_newsletter_subscribe_attempt(text, integer, interval) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.consume_newsletter_subscribe_attempt(text, integer, interval) TO service_role;

COMMENT ON TABLE public.newsletter_subscribe_attempts IS
  'Newsletter signup timestamps keyed by a salted SHA-256 IP hash. Raw IP addresses are never stored.';

-- Defense in depth: the route now writes via the service role after content
-- validation, but the anon key is still public in the client bundle, so close
-- off direct PostgREST inserts that skip app-level checks.
DROP POLICY IF EXISTS "Anyone can subscribe" ON public.subscribers;
CREATE POLICY "Anyone can subscribe with required fields"
  ON public.subscribers FOR INSERT
  WITH CHECK (
    first_name IS NOT NULL AND length(trim(first_name)) > 0 AND length(first_name) <= 100 AND
    last_name IS NOT NULL AND length(trim(last_name)) > 0 AND length(last_name) <= 100 AND
    email IS NOT NULL AND email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$' AND length(email) <= 254
  );
