-- Harden the contact/advertising-enquiry pipeline against automated spam submissions.
-- Mirrors the writer-application rate-limit pattern: only a one-way SHA-256 hash of the
-- submitter's IP is stored, never the raw address.

CREATE TABLE IF NOT EXISTS public.contact_message_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contact_message_attempts_hash_created
  ON public.contact_message_attempts (ip_hash, created_at DESC);

ALTER TABLE public.contact_message_attempts ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.consume_contact_message_attempt(
  p_ip_hash text,
  p_limit integer DEFAULT 8,
  p_window interval DEFAULT interval '1 hour'
)
RETURNS TABLE (allowed boolean, attempts integer, retry_after_seconds integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
  v_oldest timestamptz;
BEGIN
  IF p_ip_hash IS NULL OR length(p_ip_hash) <> 64 OR p_limit < 1 THEN
    RAISE EXCEPTION 'Invalid rate-limit parameters';
  END IF;

  -- Serialize requests for the same hash to prevent concurrent limit bypasses.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_ip_hash, 0));

  SELECT count(*)::integer, min(created_at)
  INTO v_count, v_oldest
  FROM public.contact_message_attempts
  WHERE ip_hash = p_ip_hash
    AND created_at > now() - p_window;

  IF v_count >= p_limit THEN
    RETURN QUERY SELECT
      false,
      v_count,
      greatest(1, ceil(extract(epoch FROM ((v_oldest + p_window) - now())))::integer);
    RETURN;
  END IF;

  INSERT INTO public.contact_message_attempts (ip_hash) VALUES (p_ip_hash);
  RETURN QUERY SELECT true, v_count + 1, 0;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_contact_message_attempt(text, integer, interval) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.consume_contact_message_attempt(text, integer, interval) TO service_role;

COMMENT ON TABLE public.contact_message_attempts IS
  'Contact/advertising-enquiry submission timestamps keyed by a salted SHA-256 IP hash. Raw IP addresses are never stored.';

-- Defense in depth: the app routes now write via the service role (bypassing RLS) after
-- content validation, but the anon key is still public in the client bundle, so anyone
-- could otherwise insert directly against PostgREST. Close that off: require every field,
-- cap lengths, and require a syntactically plausible email so a direct bypass can only
-- ever produce shaped junk, not arbitrarily large or malformed rows.
DROP POLICY IF EXISTS "Anyone can submit contact message with required fields" ON contact_messages;
CREATE POLICY "Anyone can submit contact message with required fields"
  ON contact_messages FOR INSERT
  WITH CHECK (
    name IS NOT NULL AND length(trim(name)) > 0 AND length(name) <= 200 AND
    email IS NOT NULL AND email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$' AND length(email) <= 254 AND
    subject IS NOT NULL AND length(trim(subject)) > 0 AND length(subject) <= 300 AND
    message IS NOT NULL AND length(trim(message)) > 0 AND length(message) <= 8000
  );
